image:
    file: .gitpod.Dockerfile

tasks:
  - init: mvn test-compile

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - eamodio.gitlens
    - redhat.fabric8-analytics
    - redhat.vscode-xml
